2022-11-09 09:44:04,192 Converting data/part90/in/kerala/2015/2015_047_079.pdf to img...
2022-11-09 09:44:15,309 Parsing first and last page data..
2022-11-09 09:44:19,141 Detecting and parsing data/part90/in/kerala/2015/2015_047_079.pdf boxes..
2022-11-09 09:44:19,141 Processing page 3
2022-11-09 09:44:49,440 Processing page 4
2022-11-09 09:45:16,036 Processing page 5
2022-11-09 09:45:40,484 Processing page 6
2022-11-09 09:46:14,331 Processing page 7
2022-11-09 09:46:44,329 Processing page 8
2022-11-09 09:47:12,125 Processing page 9
2022-11-09 09:47:43,514 Processing page 10
2022-11-09 09:48:20,249 Processing page 11
2022-11-09 09:48:56,741 Processing page 12
2022-11-09 09:49:28,851 Processing page 13
2022-11-09 09:50:06,282 Processing page 14
2022-11-09 09:50:39,257 Processing page 15
2022-11-09 09:50:42,675 Processing page 16
2022-11-09 09:51:17,112 Processing page 17
2022-11-09 09:51:53,915 Processing page 18
2022-11-09 09:52:23,976 Processing page 19
2022-11-09 09:52:53,635 Processing page 20
2022-11-09 09:53:30,172 Processing page 21
2022-11-09 09:54:05,480 Processing page 22
2022-11-09 09:54:32,492 Processing page 23
2022-11-09 09:55:08,349 Processing page 24
2022-11-09 09:55:42,468 Processing page 25
2022-11-09 09:56:13,479 Processing page 26
2022-11-09 09:56:50,197 Processing page 27
2022-11-09 09:57:26,472 Processing page 28
2022-11-09 09:57:56,720 Processing page 29
2022-11-09 09:58:31,517 Processing page 30
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 136-139: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught adomalog civ Od>. O.NIVIMEMNG MIDS OrderedDict([('number', '813'), ('id', 'KL/06/038/498090'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d41\u0d2d\u0d3e\u0d37\u0d3f\u0d23\u0d3f')])"
Arguments: ()
2022-11-09 09:58:34,638 Split uncaught adomalog civ Od>. O.NIVIMEMNG MIDS OrderedDict([('number', '813'), ('id', 'KL/06/038/498090'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d41\u0d2d\u0d3e\u0d37\u0d3f\u0d23\u0d3f')])

#################
Epilogue Job Info:
Job ID: 467116[90].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-90
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:14:58,vmem=2366928kb,walltime=00:15:19,mem=1401804kb,energy_used=0
Exit Code: 271
#################

