2022-11-09 09:43:57,477 Converting data/part28/in/kerala/2015/2015_014_115.pdf to img...
2022-11-09 09:44:10,151 Parsing first and last page data..
2022-11-09 09:44:12,894 Detecting and parsing data/part28/in/kerala/2015/2015_014_115.pdf boxes..
2022-11-09 09:44:12,894 Processing page 3
2022-11-09 09:44:14,250 Processing page 4
2022-11-09 09:44:48,009 Processing page 5
2022-11-09 09:45:20,314 Processing page 6
2022-11-09 09:45:55,367 Processing page 7
2022-11-09 09:46:30,943 Processing page 8
2022-11-09 09:47:08,163 Processing page 9
2022-11-09 09:47:43,262 Processing page 10
2022-11-09 09:48:16,290 Processing page 11
2022-11-09 09:48:51,960 Processing page 12
2022-11-09 09:49:26,919 Processing page 13
2022-11-09 09:50:00,944 Processing page 14
2022-11-09 09:50:39,170 Processing page 15
2022-11-09 09:50:55,780 Processing page 16
2022-11-09 09:51:29,385 Processing page 17
2022-11-09 09:52:03,419 Processing page 18
2022-11-09 09:52:39,382 Processing page 19
2022-11-09 09:53:13,486 Processing page 20
2022-11-09 09:53:47,045 Processing page 21
2022-11-09 09:54:21,942 Processing page 22
2022-11-09 09:54:56,055 Processing page 23
2022-11-09 09:55:31,124 Processing page 24
2022-11-09 09:56:07,821 Processing page 25
2022-11-09 09:56:38,618 Processing page 26
2022-11-09 09:57:13,740 Processing page 27
2022-11-09 09:57:49,499 Processing page 28
2022-11-09 09:58:19,663 Processing page 29
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 121-124: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught allgyeaie OOOH E> QI BOEING OrderedDict([('number', '['), ('id', '1120217505'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d28\u0d2f\u0d40\u0d2e\u0d1f\u0d3f\u0d15\u0d46'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d4d\\u200c \u0d1f\u0d3f\u0d15\u0d46')])"
Arguments: ()
2022-11-09 09:58:31,218 Split uncaught allgyeaie OOOH E> QI BOEING OrderedDict([('number', '['), ('id', '1120217505'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d28\u0d2f\u0d40\u0d2e\u0d1f\u0d3f\u0d15\u0d46'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d4d\u200c \u0d1f\u0d3f\u0d15\u0d46')])
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 123-126: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught allgyeaie OOOH E> QI BOEING OrderedDict([('number', '743'), ('id', 'ITZ0216424'), ('\u0d2a\u0d47\u0d30\u0d4d', 'dass j) od'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d4d\\u200c \u0d1f\u0d3f\u0d15\u0d46')])"
Arguments: ()
2022-11-09 09:58:45,734 Split uncaught allgyeaie OOOH E> QI BOEING OrderedDict([('number', '743'), ('id', 'ITZ0216424'), ('\u0d2a\u0d47\u0d30\u0d4d', 'dass j) od'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d4d\u200c \u0d1f\u0d3f\u0d15\u0d46')])

#################
Epilogue Job Info:
Job ID: 467116[28].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-28
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:14:55,vmem=2362568kb,walltime=00:15:13,mem=1397192kb,energy_used=0
Exit Code: 271
#################

