2022-11-03 11:14:40,303 Converting data/part112/in/kerala/2016/2016_059_031.pdf to img...
2022-11-03 11:14:48,896 Parsing first and last page data..
2022-11-03 11:15:00,948 Detecting and parsing data/part112/in/kerala/2016/2016_059_031.pdf boxes..
2022-11-03 11:15:00,948 Processing page 3
2022-11-03 11:15:35,408 Processing page 4
2022-11-03 11:16:10,953 Processing page 5
2022-11-03 11:16:46,236 Processing page 6
2022-11-03 11:17:20,919 Processing page 7
2022-11-03 11:17:56,485 Processing page 8
2022-11-03 11:18:31,798 Processing page 9
2022-11-03 11:19:07,330 Processing page 10
2022-11-03 11:19:42,684 Processing page 11
2022-11-03 11:20:17,740 Processing page 12
2022-11-03 11:20:51,970 Processing page 13
2022-11-03 11:21:27,079 Processing page 14
2022-11-03 11:22:02,370 Processing page 15
2022-11-03 11:22:38,145 Processing page 16
2022-11-03 11:23:14,142 Processing page 17
2022-11-03 11:23:30,625 Processing page 18
2022-11-03 11:24:05,998 Processing page 19
2022-11-03 11:24:40,077 Processing page 20
2022-11-03 11:25:14,175 Processing page 21
2022-11-03 11:25:48,363 Processing page 22
2022-11-03 11:26:23,785 Processing page 23
2022-11-03 11:26:58,325 Processing page 24
2022-11-03 11:27:32,689 Processing page 25
2022-11-03 11:28:07,011 Processing page 26
2022-11-03 11:28:41,465 Processing page 27
2022-11-03 11:29:15,325 Processing page 28
2022-11-03 11:29:49,240 Processing page 29
2022-11-03 11:30:23,459 Processing page 30
2022-11-03 11:30:58,011 Processing page 31
2022-11-03 11:31:32,598 Processing page 32
2022-11-03 11:32:05,931 Processing page 33
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 127-130: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught sdomoalag eos O.210}d>)3) OrderedDict([('number', '900'), ('id', 'KL/07/051/336453'), ('\u0d2a\u0d47\u0d30\u0d4d', 'orcoro)')])"
Arguments: ()
2022-11-03 11:32:22,653 Split uncaught sdomoalag eos O.210}d>)3) OrderedDict([('number', '900'), ('id', 'KL/07/051/336453'), ('\u0d2a\u0d47\u0d30\u0d4d', 'orcoro)')])
2022-11-03 11:32:40,021 Processing page 34
2022-11-03 11:33:15,173 Processing page 35
2022-11-03 11:33:50,417 Processing page 36
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 117-124: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: 'Split uncaught ANgySn1e" Od> Och BBo OrderedDict([(\'number\', \'994\'), (\'id\', \'NCP0259671\'), (\'\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d\', \'\u0d06\u0d23\u0d4d\u0d1f\u0d3f\')])'
Arguments: ()
2022-11-03 11:34:08,468 Split uncaught ANgySn1e" Od> Och BBo OrderedDict([('number', '994'), ('id', 'NCP0259671'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d06\u0d23\u0d4d\u0d1f\u0d3f')])
2022-11-03 11:34:26,264 Processing page 37
2022-11-03 11:35:01,207 Processing page 38
2022-11-03 11:35:36,422 Processing page 39
2022-11-03 11:36:11,507 Processing page 40
2022-11-03 11:36:46,673 Processing page 41
2022-11-03 11:37:21,113 Processing page 42
2022-11-03 11:37:56,638 Processing page 43
2022-11-03 11:38:32,162 Processing page 44
/share/svasudevan2lab/gs-delhi/parse_unsearchable_rolls/scripts/kerala/joblist_2016/kerala112.sh: line 1: 56261 Killed                  python scripts/kerala/kerala_2016.py data/part112/

#################
Epilogue Job Info:
Job ID: 466350[112].acropolis
User ID: t-9adar
Job Name: Kerala2016JobArray-112
Resource List: nodes=1:ppn=1,mem=2gb,neednodes=1:ppn=1
Resources Used: cput=00:23:09,vmem=3486492kb,walltime=00:24:24,mem=2094976kb,energy_used=0
Exit Code: 137
Exit code 137 job terminated, resource limit violation
Generally this means you need to request more RAM or CPU
Please compare your resources used/requested
#################

