2022-11-03 11:14:36,748 Converting data/part132/in/kerala/2016/2016_069_033.pdf to img...
2022-11-03 11:14:45,324 Parsing first and last page data..
2022-11-03 11:14:53,324 Detecting and parsing data/part132/in/kerala/2016/2016_069_033.pdf boxes..
2022-11-03 11:14:53,324 Processing page 3
2022-11-03 11:15:27,980 Processing page 4
2022-11-03 11:16:01,301 Processing page 5
2022-11-03 11:16:36,514 Processing page 6
2022-11-03 11:17:11,005 Processing page 7
2022-11-03 11:17:45,915 Processing page 8
2022-11-03 11:18:21,009 Processing page 9
2022-11-03 11:18:56,995 Processing page 10
2022-11-03 11:19:32,576 Processing page 11
2022-11-03 11:20:08,357 Processing page 12
2022-11-03 11:20:44,298 Processing page 13
2022-11-03 11:21:20,219 Processing page 14
2022-11-03 11:21:55,377 Processing page 15
2022-11-03 11:22:30,090 Processing page 16
2022-11-03 11:23:05,728 Processing page 17
2022-11-03 11:23:41,869 Processing page 18
2022-11-03 11:24:17,208 Processing page 19
2022-11-03 11:24:53,743 Processing page 20
2022-11-03 11:25:28,493 Processing page 21
2022-11-03 11:26:03,337 Processing page 22
2022-11-03 11:26:39,342 Processing page 23
2022-11-03 11:27:14,110 Processing page 24
2022-11-03 11:27:49,254 Processing page 25
2022-11-03 11:28:24,243 Processing page 26
2022-11-03 11:28:58,651 Processing page 27
2022-11-03 11:29:34,407 Processing page 28
2022-11-03 11:30:09,379 Processing page 29
2022-11-03 11:30:43,881 Processing page 30
2022-11-03 11:31:19,492 Processing page 31
2022-11-03 11:31:54,969 Processing page 32
2022-11-03 11:32:30,242 Processing page 33
2022-11-03 11:33:05,191 Processing page 34
2022-11-03 11:33:41,008 Processing page 35
2022-11-03 11:34:16,234 Processing page 36
2022-11-03 11:34:52,307 Processing page 37
2022-11-03 11:35:27,652 Processing page 38
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 126-129: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught Bdomalag eae WUble>J 2B OrderedDict([('number', '1067'), ('id', 'KL/09/066/420522'), ('\u0d2a\u0d47\u0d30\u0d4d', 'ole')])"
Arguments: ()
2022-11-03 11:35:44,531 Split uncaught Bdomalag eae WUble>J 2B OrderedDict([('number', '1067'), ('id', 'KL/09/066/420522'), ('\u0d2a\u0d47\u0d30\u0d4d', 'ole')])
2022-11-03 11:36:02,337 Processing page 39
2022-11-03 11:36:39,366 Processing page 40
2022-11-03 11:37:12,169 Processing page 41
2022-11-03 11:37:15,491 Formatting and exporting data/part132/in/kerala/2016/2016_069_033.pdf data..
2022-11-03 11:37:15,935 Converted to csv: data/out/kerala/2016/2016_069_033.csv
2022-11-03 11:37:16,004 Converting data/part132/in/kerala/2016/2016_069_034.pdf to img...
2022-11-03 11:37:27,312 Parsing first and last page data..
2022-11-03 11:37:47,970 Detecting and parsing data/part132/in/kerala/2016/2016_069_034.pdf boxes..
2022-11-03 11:37:47,970 Processing page 3
2022-11-03 11:38:22,359 Processing page 4
2022-11-03 11:38:57,257 Processing page 5
2022-11-03 11:39:31,573 Processing page 6
2022-11-03 11:40:05,896 Processing page 7
2022-11-03 11:40:40,199 Processing page 8
2022-11-03 11:41:12,976 Processing page 9
2022-11-03 11:41:29,528 Split uncaught Gale O&>).2j0078) OrderedDict([('number', '200'), ('id', 'KL/09/066/384437')])
2022-11-03 11:41:45,972 Processing page 10
2022-11-03 11:42:20,326 Processing page 11
2022-11-03 11:42:54,304 Processing page 12
2022-11-03 11:43:29,040 Processing page 13
2022-11-03 11:44:02,666 Processing page 14
2022-11-03 11:44:36,476 Processing page 15
2022-11-03 11:45:11,394 Processing page 16
2022-11-03 11:45:46,463 Processing page 17
2022-11-03 11:46:20,086 Processing page 18
2022-11-03 11:46:55,279 Processing page 19
2022-11-03 11:47:28,735 Processing page 20
2022-11-03 11:48:02,346 Processing page 21
2022-11-03 11:48:36,379 Processing page 22
2022-11-03 11:49:10,253 Processing page 23
2022-11-03 11:49:43,443 Processing page 24
2022-11-03 11:50:17,094 Processing page 25
2022-11-03 11:50:51,834 Processing page 26
2022-11-03 11:51:25,986 Processing page 27
2022-11-03 11:51:59,982 Processing page 28
2022-11-03 11:52:34,302 Processing page 29
2022-11-03 11:53:07,851 Processing page 30
2022-11-03 11:53:41,355 Processing page 31
2022-11-03 11:54:14,367 Processing page 32
2022-11-03 11:54:47,588 Processing page 33
2022-11-03 11:55:20,951 Processing page 34
2022-11-03 11:55:55,144 Processing page 35
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 123-126: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught sdomalag ete AGMNIE Okr.OL> OrderedDict([('number', '963'), ('id', 'DBD1079128'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d28\u0d4d\u0d27\u0d4d\u0d2f af.')])"
Arguments: ()
2022-11-03 11:56:26,747 Split uncaught sdomalag ete AGMNIE Okr.OL> OrderedDict([('number', '963'), ('id', 'DBD1079128'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d28\u0d4d\u0d27\u0d4d\u0d2f af.')])
2022-11-03 11:56:28,321 Processing page 36
2022-11-03 11:57:01,373 Processing page 37
2022-11-03 11:57:34,537 Processing page 38
2022-11-03 11:58:07,797 Processing page 39
2022-11-03 11:58:42,394 Processing page 40
2022-11-03 11:59:15,526 Processing page 41
2022-11-03 11:59:48,519 Processing page 42
/share/svasudevan2lab/gs-delhi/parse_unsearchable_rolls/scripts/kerala/joblist_2016/kerala132.sh: line 1:  1512 Killed                  python scripts/kerala/kerala_2016.py data/part132/

#################
Epilogue Job Info:
Job ID: 466350[132].acropolis
User ID: t-9adar
Job Name: Kerala2016JobArray-132
Resource List: nodes=1:ppn=1,mem=2gb,neednodes=1:ppn=1
Resources Used: cput=00:44:02,vmem=3329680kb,walltime=00:45:40,mem=2049080kb,energy_used=0
Exit Code: 137
Exit code 137 job terminated, resource limit violation
Generally this means you need to request more RAM or CPU
Please compare your resources used/requested
#################

